"""add_user_form_settings

Revision ID: 313043d00dbc
Revises: 97168f34447a
Create Date: 2025-12-17 15:20:53.063844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313043d00dbc'
down_revision: Union[str, Sequence[str], None] = '97168f34447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_form_settings',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('form_id', sa.String(length=100), nullable=False),
        sa.Column('settings_type', sa.String(length=50), nullable=False),
        sa.Column('settings_data', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'form_id', 'settings_type', name='uq_user_form_settings')
    )
    op.create_index('idx_user_form_settings_lookup', 'user_form_settings', ['user_id', 'form_id'], unique=False)

    op.create_table('form_command_configuration',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('form_id', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('command_id', sa.String(length=100), nullable=False),
        sa.Column('is_visible', sa.Boolean(), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('is_in_more_menu', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('form_id', 'user_id', 'command_id', name='uq_form_command_config')
    )
    op.create_index('idx_form_command_config', 'form_command_configuration', ['form_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_form_command_config', table_name='form_command_configuration')
    op.drop_table('form_command_configuration')
    op.drop_index('idx_user_form_settings_lookup', table_name='user_form_settings')
    op.drop_table('user_form_settings')
    # ### end Alembic commands ###
