"""Initial schema

Revision ID: 201f5ef24462
Revises: 
Create Date: 2025-11-28 01:08:20.664093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201f5ef24462'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constants', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('counterparties', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('counterparties', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('counterparties', 'inn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('counterparties', 'contact_person',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('counterparties', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('counterparties', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('counterparties', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('daily_report_executors', 'report_line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_report_executors', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'daily_report_executors', type_='foreignkey')
    op.create_foreign_key(None, 'daily_report_executors', 'daily_report_lines', ['report_line_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_report_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('daily_report_lines', 'report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_report_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_report_lines', 'planned_labor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'actual_labor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'deviation_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'group_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'is_collapsed',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_daily_report_lines_report_id'), 'daily_report_lines', ['report_id'], unique=False)
    op.drop_constraint(None, 'daily_report_lines', type_='foreignkey')
    op.create_foreign_key(None, 'daily_report_lines', 'daily_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('daily_reports', 'number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('daily_reports', 'is_posted',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'posted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('daily_reports', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'modified_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_daily_reports_date'), table_name='daily_reports')
    op.drop_index(op.f('idx_daily_reports_estimate'), table_name='daily_reports')
    op.create_index(op.f('ix_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.create_index(op.f('ix_daily_reports_estimate_id'), 'daily_reports', ['estimate_id'], unique=False)
    op.alter_column('estimate_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('estimate_lines', 'estimate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('estimate_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('estimate_lines', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'labor_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'sum',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'planned_labor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'group_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'is_collapsed',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_estimate_lines_estimate_id'), 'estimate_lines', ['estimate_id'], unique=False)
    op.drop_constraint(None, 'estimate_lines', type_='foreignkey')
    op.create_foreign_key(None, 'estimate_lines', 'estimates', ['estimate_id'], ['id'], ondelete='CASCADE')
    op.alter_column('estimates', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('estimates', 'number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('estimates', 'total_sum',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimates', 'total_labor',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('estimates', 'is_posted',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('estimates', 'posted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('estimates', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('estimates', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('estimates', 'modified_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_estimates_date'), table_name='estimates')
    op.drop_index(op.f('idx_estimates_responsible'), table_name='estimates')
    op.create_index(op.f('ix_estimates_date'), 'estimates', ['date'], unique=False)
    op.create_index(op.f('ix_estimates_responsible_id'), 'estimates', ['responsible_id'], unique=False)
    op.alter_column('objects', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('objects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('objects', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('objects', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'inn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('organizations', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('organizations', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('payroll_register', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('payroll_register', 'recorder_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('payroll_register', 'hours_worked',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('payroll_register', 'amount',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('payroll_register', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_payroll_date'), table_name='payroll_register')
    op.create_index(op.f('ix_payroll_register_employee_id'), 'payroll_register', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_register_estimate_id'), 'payroll_register', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_payroll_register_object_id'), 'payroll_register', ['object_id'], unique=False)
    op.create_index(op.f('ix_payroll_register_period'), 'payroll_register', ['period'], unique=False)
    op.create_index(op.f('ix_payroll_register_recorder_id'), 'payroll_register', ['recorder_id'], unique=False)
    op.create_index(op.f('ix_payroll_register_recorder_type'), 'payroll_register', ['recorder_type'], unique=False)
    op.create_index(op.f('ix_payroll_register_work_date'), 'payroll_register', ['work_date'], unique=False)
    op.create_unique_constraint('uq_payroll_entry', 'payroll_register', ['object_id', 'estimate_id', 'employee_id', 'work_date'])
    op.alter_column('persons', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('persons', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('persons', 'position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('persons', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('persons', 'hourly_rate',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('persons', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('persons', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('timesheet_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('timesheet_lines', 'timesheet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('timesheet_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('timesheet_lines', 'hourly_rate',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_01',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_02',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_03',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_04',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_05',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_06',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_07',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_08',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_09',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_10',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_11',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_12',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_13',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_14',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_15',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_16',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_17',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_18',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_19',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_20',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_21',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_22',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_23',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_24',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_25',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_26',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_27',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_28',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_29',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_30',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_31',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'total_hours',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'total_amount',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_timesheet_lines_employee'), table_name='timesheet_lines')
    op.drop_index(op.f('idx_timesheet_lines_timesheet'), table_name='timesheet_lines')
    op.create_index(op.f('ix_timesheet_lines_employee_id'), 'timesheet_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheet_lines_timesheet_id'), 'timesheet_lines', ['timesheet_id'], unique=False)
    op.drop_constraint(None, 'timesheet_lines', type_='foreignkey')
    op.create_foreign_key(None, 'timesheet_lines', 'timesheets', ['timesheet_id'], ['id'], ondelete='CASCADE')
    op.alter_column('timesheets', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('timesheets', 'number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('timesheets', 'month_year',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('timesheets', 'is_posted',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('timesheets', 'posted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('timesheets', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('timesheets', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('timesheets', 'modified_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_timesheets_date'), table_name='timesheets')
    op.drop_index(op.f('idx_timesheets_estimate'), table_name='timesheets')
    op.drop_index(op.f('idx_timesheets_foreman'), table_name='timesheets')
    op.drop_index(op.f('idx_timesheets_object'), table_name='timesheets')
    op.create_index(op.f('ix_timesheets_date'), 'timesheets', ['date'], unique=False)
    op.create_index(op.f('ix_timesheets_estimate_id'), 'timesheets', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_timesheets_foreman_id'), 'timesheets', ['foreman_id'], unique=False)
    op.create_index(op.f('ix_timesheets_object_id'), 'timesheets', ['object_id'], unique=False)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_settings', 'form_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('user_settings', 'setting_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('work_execution_register', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('work_execution_register', 'recorder_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('work_execution_register', 'quantity_income',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'quantity_expense',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'sum_income',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'sum_expense',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_work_execution_register_estimate_id'), 'work_execution_register', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_work_execution_register_object_id'), 'work_execution_register', ['object_id'], unique=False)
    op.create_index(op.f('ix_work_execution_register_period'), 'work_execution_register', ['period'], unique=False)
    op.create_index(op.f('ix_work_execution_register_recorder_id'), 'work_execution_register', ['recorder_id'], unique=False)
    op.create_index(op.f('ix_work_execution_register_recorder_type'), 'work_execution_register', ['recorder_type'], unique=False)
    op.create_index(op.f('ix_work_execution_register_work_id'), 'work_execution_register', ['work_id'], unique=False)
    op.alter_column('works', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('works', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('works', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('works', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('works', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('works', 'labor_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('works', 'is_group',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('works', 'marked_for_deletion',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('works', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('works', 'labor_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('works', 'price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('works', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('works', 'code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('works', 'name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('works', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_work_execution_register_work_id'), table_name='work_execution_register')
    op.drop_index(op.f('ix_work_execution_register_recorder_type'), table_name='work_execution_register')
    op.drop_index(op.f('ix_work_execution_register_recorder_id'), table_name='work_execution_register')
    op.drop_index(op.f('ix_work_execution_register_period'), table_name='work_execution_register')
    op.drop_index(op.f('ix_work_execution_register_object_id'), table_name='work_execution_register')
    op.drop_index(op.f('ix_work_execution_register_estimate_id'), table_name='work_execution_register')
    op.alter_column('work_execution_register', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'sum_expense',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'sum_income',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'quantity_expense',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'quantity_income',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('work_execution_register', 'recorder_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('work_execution_register', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               server_default=sa.text('1'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('user_settings', 'setting_key',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user_settings', 'form_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_timesheets_object_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_foreman_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_estimate_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_date'), table_name='timesheets')
    op.create_index(op.f('idx_timesheets_object'), 'timesheets', ['object_id'], unique=False)
    op.create_index(op.f('idx_timesheets_foreman'), 'timesheets', ['foreman_id'], unique=False)
    op.create_index(op.f('idx_timesheets_estimate'), 'timesheets', ['estimate_id'], unique=False)
    op.create_index(op.f('idx_timesheets_date'), 'timesheets', ['date'], unique=False)
    op.alter_column('timesheets', 'modified_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('timesheets', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('timesheets', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('timesheets', 'posted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('timesheets', 'is_posted',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('timesheets', 'month_year',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('timesheets', 'number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('timesheets', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'timesheet_lines', type_='foreignkey')
    op.create_foreign_key(None, 'timesheet_lines', 'timesheets', ['timesheet_id'], ['id'])
    op.drop_index(op.f('ix_timesheet_lines_timesheet_id'), table_name='timesheet_lines')
    op.drop_index(op.f('ix_timesheet_lines_employee_id'), table_name='timesheet_lines')
    op.create_index(op.f('idx_timesheet_lines_timesheet'), 'timesheet_lines', ['timesheet_id'], unique=False)
    op.create_index(op.f('idx_timesheet_lines_employee'), 'timesheet_lines', ['employee_id'], unique=False)
    op.alter_column('timesheet_lines', 'total_amount',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'total_hours',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_31',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_30',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_29',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_28',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_27',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_26',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_25',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_24',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_23',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_22',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_21',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_20',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_19',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_18',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_17',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_16',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_15',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_14',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_13',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_12',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_11',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_10',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_09',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_08',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_07',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_06',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_05',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_04',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_03',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_02',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'day_01',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'hourly_rate',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('timesheet_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timesheet_lines', 'timesheet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timesheet_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('persons', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('persons', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('persons', 'hourly_rate',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('persons', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persons', 'position',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persons', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('persons', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_payroll_entry', 'payroll_register', type_='unique')
    op.drop_index(op.f('ix_payroll_register_work_date'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_recorder_type'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_recorder_id'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_period'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_object_id'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_estimate_id'), table_name='payroll_register')
    op.drop_index(op.f('ix_payroll_register_employee_id'), table_name='payroll_register')
    op.create_index(op.f('idx_payroll_date'), 'payroll_register', ['work_date'], unique=False)
    op.alter_column('payroll_register', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payroll_register', 'amount',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('payroll_register', 'hours_worked',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('payroll_register', 'recorder_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payroll_register', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('organizations', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('organizations', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organizations', 'inn',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('objects', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('objects', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('objects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('objects', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_estimates_responsible_id'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_date'), table_name='estimates')
    op.create_index(op.f('idx_estimates_responsible'), 'estimates', ['responsible_id'], unique=False)
    op.create_index(op.f('idx_estimates_date'), 'estimates', ['date'], unique=False)
    op.alter_column('estimates', 'modified_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('estimates', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('estimates', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('estimates', 'posted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('estimates', 'is_posted',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('estimates', 'total_labor',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimates', 'total_sum',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimates', 'number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('estimates', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'estimate_lines', type_='foreignkey')
    op.create_foreign_key(None, 'estimate_lines', 'estimates', ['estimate_id'], ['id'])
    op.drop_index(op.f('ix_estimate_lines_estimate_id'), table_name='estimate_lines')
    op.alter_column('estimate_lines', 'is_collapsed',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'group_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'planned_labor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'sum',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'labor_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('estimate_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('estimate_lines', 'estimate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('estimate_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_daily_reports_estimate_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_date'), table_name='daily_reports')
    op.create_index(op.f('idx_daily_reports_estimate'), 'daily_reports', ['estimate_id'], unique=False)
    op.create_index(op.f('idx_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.alter_column('daily_reports', 'modified_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_reports', 'posted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'is_posted',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'daily_report_lines', type_='foreignkey')
    op.create_foreign_key(None, 'daily_report_lines', 'daily_reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_daily_report_lines_report_id'), table_name='daily_report_lines')
    op.alter_column('daily_report_lines', 'is_collapsed',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'group_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'deviation_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'actual_labor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'planned_labor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_report_lines', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_report_lines', 'report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_report_lines', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'daily_report_executors', type_='foreignkey')
    op.create_foreign_key(None, 'daily_report_executors', 'daily_report_lines', ['report_line_id'], ['id'])
    op.alter_column('daily_report_executors', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_report_executors', 'report_line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('counterparties', 'marked_for_deletion',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('counterparties', 'is_group',
               existing_type=sa.Boolean(),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('counterparties', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('counterparties', 'contact_person',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('counterparties', 'inn',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('counterparties', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('counterparties', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('constants', 'key',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
